### ISSUE TITLE
Contrasts: MAST format

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#128]
In addition to the limma format, we can add the MAST format, by adding the following line to clusterContrasts

``` r
if(outputType=="MAST") return(MAST::Hypothesis(contrastNames, levnames))
```

**Comment by drisso** [comment]
The problem is that MAST is not on CRAN or Bioconductor, but only on github, and it's not clear if a Bioconductor paclkage can import github packages.

**Comment by epurdom** [comment]
@drisso: MAST is now on bioconductor. Could you update the code to allow for MAST contrasts?

**Comment by epurdom** [comment]
Have now added line of code to develop.
