### ISSUE TITLE
clusterSamplesData doesn't seem to work for plotCoClustering

### ISSUE THREAD

**Issue by epurdom** [epurdom/clusterExperiment#129]
So you can't, for example, cluster on dendrogram.

**Comment by drisso** [comment]
Yes, I've noticed this too analyzing the brain data. Minimal example:

```{r}
cl = clusterMany(simData, ks=2:6, clusterFunction="pam")
cl = combineMany(cl, proportion=.7)
plotCoClustering(cl) #this works
cl = makeDendrogram(cl)
plotCoClustering(cl)
```

The second call gives

```{r}
Error in validObject(fakeCE) : 
  invalid class “ClusterExperiment” object: dendro_clusters should not be null if dendro_samples is non-null
```

**Comment by drisso** [comment]
Or is this a different issue?

**Comment by drisso** [comment]
Also we should probably add this as a test for plotCoClustering.

**Comment by epurdom** [comment]
This is a different issue which I've fixed and will push (part of changing the dendrogram structures).

**Comment by drisso** [comment]
OK, sorry for the confusion.

**Comment by epurdom** [comment]
Clarification, it did not give an error, it just ignored clusterSamplesData options.

This is a problem with isSymmetric option in matrix version of plotHeatmap. It ignores clusterSamplesData and uses only clusterFeaturesData input, which is arbitrary. Have now switched it so uses the clusterSamplesData feature and ignores clusterFeaturesData input. This makes more sense, because it is the samples being clustered, and moreover in fact plotCoClustering calls the *clusterExperiment* version of plotHeatmap and sets clusterFeaturesData="all" (which is then converted before the call to matrix version of plotHeatmap), so that is the option that should not be set.

Just pushed correction to 'develop'.
