### ISSUE TITLE
whichClusters in plotHeatmap does not work as intended when using clusterLabels values

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#133]
The following example (from the vignette) does not show the "combineMany,final" clustering.

```{r}
plotHeatmap(ce,clusterSamplesData="dendrogramValue",
            whichClusters=c("mergeClusters","combineMany,final"),
            main="Heatmap with clusterMany",
            sampleData=c("Biological_Condition","Cluster2"),annLegend=FALSE)
```

It only displays the mergeClusters. Changing that to "combineMany" works -- I suspect this is because it reads it from clusterType?

**Comment by epurdom** [comment]
This is due to the fact that it first checks to see if match to clusterType and then if match to clusterLabel. Should fix this to be more sensititve.

**Comment by epurdom** [comment]
Fixed this. Now pushed to develop.
