### ISSUE TITLE
makeDendrogram with most variable ignore -1 clusterings and do PCA on top most variable for speed?

### ISSUE THREAD

**Issue by epurdom** [epurdom/clusterExperiment#135]
Davide's current code removes samples with -1 clustering to find the most variable:

wh_rm <- which(final_tight == -1)
vars <- apply(transform(cl)[,-wh_rm], 1, var)
vars <- sort(vars, decreasing=TRUE)
pca_v <- prcomp(t(transform(cl)[names(vars)[1:1000],]), center = TRUE, scale. = TRUE)
dendro <- makeDendrogram(t(pca_v$x[,1:50]), final_tight)

**Comment by epurdom** [comment]
@drisso I have added an option to remove the -1 for finding the most variable in .transData, and have added this option in `transform` and in `makeDendrogram`. I have pushed this feature to develop.

I have not then done PCA of that -- I am thinking this is not necessary, mainly a computational savings. What do you think

**Comment by drisso** [comment]
I don't have a strong opinion. I think it's fine to not do PCA for now.
