### ISSUE TITLE
Vignette not building

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#141]
From R CMD BiocCheck on Bioconductor machines:

* Checking whether vignette is built with 'R CMD build'...
    * REQUIRED: Vignette must be built by 'R CMD build'. Please see the
      `Vignette Checks` section of the BiocCheck vignette.

**Comment by drisso** [comment]
This is because of the vignette builder, I think that it should be knitr::markdown instead of rmarkdown::render

**Comment by epurdom** [comment]
That's confusing. There isn't a knitr::markdown in my R. I have knitr::render_markdown. But it doesn't do anything. Literally, when I run it at the command prompt for our vignette, it doesn't launch anything. I suspect that it only works after converted to markdown.

**Comment by drisso** [comment]
This is where I've found that we should use knitr:rmarkdown

http://rmarkdown.rstudio.com/package_vignette_format.html

It seems to do something during R CMD build:
* creating vignettes ... OK

Note that this wasn't happening before I changed that line in the vignette.

I need to run BiocCheck on the bioc-devel version (I wasn't and that's why I haven't realized these issues before submitting). Apparently the new version of BiocCheck has more checks.

**Comment by epurdom** [comment]
Yes, I see now on 
http://yihui.name/knitr/demo/vignette/

that there should be this option. Just weird that its not an exported function. Must be just for vignettes, somehow
<pre>
> names(vignetteEngine(package = 'knitr'))
[1] "knitr::rmarkdown"              "knitr::docco_classic_notangle" "knitr::docco_linear_notangle"  "knitr::knitr"                 
[5] "knitr::docco_classic"          "knitr::rmarkdown_notangle"     "knitr::knitr_notangle"         "knitr::docco_linear"          
> 
> knitr::rmarkdown("clusterExperimentTutorial.Rmd")
Error: 'rmarkdown' is not an exported object from 'namespace:knitr'
>
</pre>
