### ISSUE TITLE
Subscribe to bioc-devel

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#142]
From R CMD BiocCheck on Bioconductor machines:

* Checking for bioc-devel mailing list subscription...
    * REQUIRED: Maintainer should subscribe to the bioc-devel mailing
      list. Subscribe here:
      https://stat.ethz.ch/mailman/listinfo/bioc-devel

@epurdom can you please subscribe to the mailing list?

**Comment by epurdom** [comment]
@drisso Done! (epurdom@stat.berkeley.edu)
