### ISSUE TITLE
distfun not passed to aheatmap?

### ISSUE THREAD

**Issue by allonw** [epurdom/clusterExperiment#151]
The distfun argument seems to have no effect when used with plotHeatmap (that should pass it on to aheatmap). It works as expected when calling aheatmap directly.

```
library(clusterExperiment)
data(simData)

#both produce the same heatmap
plotHeatmap(simData, main="euclidean")
plotHeatmap(simData, distfun="spearman", main="spearman")

library(NMF)

#default distfun is "euclidean" so a "spearman" distfun produces, as expected,
#different dendrograms
aheatmap(simData, main="euclidean")
aheatmap(simData, distfun="spearman", main="spearman")
```

**Comment by epurdom** [comment]
Yes, I can see why the current code wouldn't pass this one to aheatmap, but we should fix the code so it does. I'll mark this as a bug. Thanks.

**Comment by epurdom** [comment]
I have corrected this on the develop branch.

**Comment by allonw** [comment]
Thanks. Are there any other parameters that are not transferred to aheatmap, or should the fix apply to all possible parameters?
