### ISSUE TITLE
Help of clusterMany

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#152]
The clusterFunction argument needs to be rewritten. Something is wrong with the roxygen formatting and the help for distFunction landed in there. Also, it refers to clusterSingle, when the man page is for clusterMany only.

It would be useful to clarify what clusterFunction choices the user has and what is the difference between them.

**Comment by drisso** [comment]
Also, there is no useful description of the alpha parameter.

**Comment by epurdom** [comment]
I have fixed this in develop.
