### ISSUE TITLE
RSEC error when run=FALSE

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#156]
```{r}
> rs <- RSEC(se, isCount=TRUE, nPCADims=c(10), alphas = c(0.1), verbose=TRUE, k0s=4:5, run=FALSE)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘combineMany’ for signature ‘"list", "character"’
```

My guess is that RSEC is not stopping after clusterMany and it's trying to run combineMany on the results of clusterMany that wasn't actually run.

**Comment by drisso** [comment]
Note that the same call with run=TRUE works.

**Comment by epurdom** [comment]
Yes, that is the problem. I can easily add a check so it stops and just returns if run=FALSE.

**Comment by epurdom** [comment]
@drisso I have pushed a fix for this to develop.
