### ISSUE TITLE
Travis CI build failing

### ISSUE THREAD

**Issue by oneillkza** [epurdom/clusterExperiment#171]
Hi! I noticed your Travis build was failing, for a similar reason to a package I'm maintaining. Apparently the solution has been patched into devtools, and you can get your build to work by adding the line:

`r_github_packages: hadley/devtools`

to your travis.yml.

Details are in this discussion:

https://github.com/travis-ci/travis-ci/issues/6244#issuecomment-235120489

**Comment by drisso** [comment]
Thanks @oneillkza !

It was indeed bothering me that the Travis build was failing, but didn't have time to look into it!

Commit cc627aedcb37e0e75ea7d4661c38e73c9528df6c implements the suggested change in the develop branch. Will be merge to master in the next release.

**Comment by oneillkza** [comment]
You're welcome! :)
