### ISSUE TITLE
How to best change a cluster

### ISSUE THREAD

**Issue by epurdom** [epurdom/clusterExperiment#176]
I have posted this from Allon so it is available more generally.

Hi,

Can I please ask a small question on this method?

Assume I have a clusterExperiment object with some clusters. I'd like
to change it a bit (e.g., switching the labels of several cells based
on prior knowledge ) without breaking the object.

From the documentation I understand that the right way to do it is to
use addClusters with signature (x = ClusterExperiment, y = matrix)

But I don't see there or in the examples the expected format of the
matrix for user-defined clusters. Can you please give an example how
to do it?

thanks
Allon

**Comment by epurdom** [comment]
@allonw Hi Allon. I posted your question on github.

It depends a bit on what you are wanting to change. If you just want to change the labels for a particular cluster (as oppose to the cluster assignments), you do not have to make a new cluster. You can just change the value in the `clusterLegend` slot of the class using the `clusterLegend` function.

In the following I create a small toy clusterExperiment object
<pre>
library(clusterExperiment)
mat <- matrix(data=rnorm(20*15), ncol=15)
mat[1,1]<- -1 #force a negative value
colnames(mat)<-paste("Sample",1:ncol(mat))
rownames(mat)<-paste("Gene",1:nrow(mat))
labMat<-cbind(as.numeric(as.character(numLabels)),as.numeric(as.character(numLabels)))
colnames(labMat)<-c("Cluster1","Cluster2")
cc <- clusterExperiment(mat, labMat, transformation = function(x){x})
</pre>

I can look at the clusterLegend and see what the labels currently are, as well as the internal index for the cluster, and the default color assigned to the cluster:
<pre>
clusterLegend(cc)
</pre>

Here I change the names of the '-1' and '-2' clusters
<pre>
clusterLegend(cc)[[2]][1:2,"name"]<-c("unassigned","missing")
clusterLegend(cc)
</pre>

If I want to instead monkey around with the cluster assignments of the second cluster and save it as a new cluster,
<pre>
x<-clusterMatrix(cc)[,2]
x[3:4]<-c(8,8)
cc<-addClusters(cc,x)
cc
clusterLabels(cc)
clusterTypes(cc)
clusterLegend(cc)
</pre>
Notice that the internal indexing of the clusters does not match the numbers of x -- they are required to be consecutive integers -- but that the cluster ids in x are given as the cluster names. In this case '8' got assigned to be '1' and not much else changed, but it could be more extensive rearrangement than that. This is why it doesn't make sense to make a new cluster merely to change the names or colors (unless you really want to have two versions of the same clustering hanging around because you are switching back and forth frequently). 

Then I can go and fix things up that cluster that will help for plotting and keeping track of this cluster. 
<pre>
clusterLabels(cc)[3]<-"My new cluster"
clusterLegend(cc)[[3]][3,"name"]<-"my new cluster"
clusterLegend(cc)[[3]][3,"color"]<-"red"
</pre>

**Comment by allonw** [comment]
Thanks for the detailed answer. Indeed, I meant the 2nd use-case ("monkeying around with the cluster assignments") - in my case, splitting a particular cluster based on a known marker gene.

PS. please note that your example code does not run as-is because numLabels is undefined

**Comment by epurdom** [comment]
Thanks, I updated the previous code to define numLabels.
