### ISSUE TITLE
On calling clusterMany on large datasets: Error in (function (classes, fdef, mtable)  :   unable to find an inherited method for function ‘primaryCluster’ for signature ‘"NULL"’ 

### ISSUE THREAD

**Issue by diyadas** [epurdom/clusterExperiment#182]
The error message in full:

```
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘primaryCluster’ for signature ‘"NULL"’
Calls: clusterMany ... sapply -> lapply -> FUN -> primaryCluster -> <Anonymous>
```

This specifically occurs with large datasets. 1272 samples runs okay (16 hours wallclock time), 1672 samples fails with this error after 1 day, 16h. We've had similar issues with other datasets of the same size. (The 1272 samples are a subset of the 1672 samples.) I would have suspected a memory issue, but it's not reporting as such.

**Comment by epurdom** [comment]
This is probably memory issue. Setting `largeDataset=TRUE` should fix it now. Closing for now.
