### ISSUE TITLE
RSEC doesn't work with mergeMethod="none"

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#214]
Here's a minimal example, using one of the objects defined in out tests:

```{r}
  rsecOut<-RSEC(x=assay(seSimCount), isCount=TRUE,dimReduce="none",
                k0s=4:5,clusterFunction="tight", alphas=0.1,
                betas=0.9,dendroReduce="none",minSizes=1,
                subsampleArgs=list(resamp.num=5),random.seed=495,
                mergeMethod="none")
```

This works in master, but currently does not work in develop. The change that caused this is the following in megeClusters()

https://github.com/epurdom/clusterExperiment/blame/develop/R/mergeClusters.R#L152

```{r}
-       ce <- do.call( mergeClusters,c(list(x=ce,plotType="none"), args1, passedArgs[c("isCount")]))
+       ce <- do.call( mergeClusters,c(list(x=ce,plot=FALSE,plotInfo="none"), args1, passedArgs[c("isCount")]))
```

Because megeClusters() will fail if both `mergeMethod="none"` and `plotInfo="none"`.

@epurdom  should we simply skip this line when mergeClusters==“none”? Alternatively, can we change the following line in mergeClusters() (https://github.com/epurdom/clusterExperiment/blob/develop/R/mergeClusters.R#L152)

```{r}
if(mergeMethod=="none" & plotInfo=="none") stop("mergeMethod and plotInfo both equal 'none'; nothing to be done.")
```

To:
```{r}
if(mergeMethod=="none" & plotInfo=="none") return(out)
```

For a sensible definition of `out` in this case. Perhaps turning the error into a warning.

What do you think?

Once we fix it, I can add the above example as a unit test.

**Comment by epurdom** [comment]
@drisso I have just pushed a catch for this in develop branch in the  `RSEC` function so that it will skip the call to `mergeClusters` if `mergeMethod="none"`.

**Comment by drisso** [comment]
Great! Thanks Elizabeth!

I've added the example as a unit test in develop!

**Comment by drisso** [comment]
I've also increased the version so that we can check it in the workflow.
