### ISSUE TITLE
Why is assignment of colors so slow?

### ISSUE THREAD

**Issue by epurdom** [epurdom/clusterExperiment#217]
I have a computational question about how we are storing colors for clusters in the clusterExperiment package. We have a list of matrices, where each element of the list corresponds to a clustering, and the matrix is a # clusters x 3 matrix. 

It takes, however, surprisingly long to manipulate elements of this list. For example, the following (non-reproducible) simple assignment took 1.8s to run on my laptop (where there are 147 clusterings saved):

clusterLegend(ceObj)[["PublishedClusters"]][m,"color"]<-publishedClustersAnno$Color

Obviously that’s not long in the scheme of things, but for a simple assignment its rather astonishingly long. It makes me wonder if there is some problem in how we are creating this list, or how we created the assignment function, that its taking so long. We create an assignment operator for replacing the entire clusterLegend slot, and this appears to work with standard built in functions to indexing the list and replace parts of it, but perhaps we should be creating such assignment operators ourself? @drisso, do you have any ideas on this?

**Comment by drisso** [comment]
I can have a look later... my first guess is that we might be copying the whole `ceObj` object with that call? If the object is large it would take a while but most importantly it can be very memory inefficient...

Using one of the objects that we define in the tests, I get the following:

```{r}
> tracemem(ccSE)
[1] "<0x1218e3ae0>"
> clusterLegend(ccSE)[["Cluster1"]][1, "color"] <- "red"
tracemem[0x1218e3ae0 -> 0x116a20878]: 
tracemem[0x116a20878 -> 0x116a1e1c8]: 
tracemem[0x116a1e1c8 -> 0x116a1d468]: clusterLegend<- clusterLegend<- 
```

If I understand correctly the output of tracemem this means that we are copying the object three times! No wonder it takes a while!

I'll have a look at the code and see what we're doing wrong here...

**Comment by epurdom** [comment]
Martin Morgan's reponse here is perhaps interesting, though its old: http://r.789695.n4.nabble.com/Doing-the-right-amount-of-copy-for-large-data-frames-td919283.html 
> The Biocondcutor package Biobase has a class 'ExpressionSet' with slot
assayData. By default assayData is an environment that is 'locked' so
can't be modified casually. The interface to ExpressionSet unlocks the
environment, and copies and modifies it when necessary. This is not
quite the same as you propose, but has some similar characteristics.

> I've spent a lot of time with this data structure, and think this
borders on one of those ideas that 'seemed like a good idea at the
time'. You end up using R-level tools to manage memory. Copy-on-change
is better than you might naively think at not making unnecessary
copies. S4 caries significant overhead, including copies during method
dispatch, that work against you (subsetting an expression set in an
OOP way, no behind-the-scenes tricks, makes *5* copies of the S4
instance, though perhaps these are light-weight because the big data
is in an environment). And in the mean time computers have gotten
faster and bigger, and the 'big' data of ExpressionSets are now only
modestly sized or even small.

> A somewhat different approach is in the Biostrings package, for
instance DNAStringSet, where the original object is 'read-only'. The
user is presented with a 'view' into the object; changing the view
(subsetting) changes the indicies in the view but not the original
data. This is both fast and memory efficient. This is a read-only
solution, though.

**Comment by drisso** [comment]
Mmm... interesting... still, there should be a solution to, say, copy the data frame containing the clusterLegend stuff but without copying the entire clusterExperiment object, no?

**Comment by drisso** [comment]
Also relevant: this comment that Martin told me at the zinbwave package submission:

helper-methods.R: Creating an object with `object@X <- ...`
`object@Y <- ...` copies object on each assignment. Consider
instead creating appropriate values, e.g., `if (missing(Y)) Y <- NULL` and then a single call to `new(..., Y=Y)`.

Is this something we can work with?

**Comment by epurdom** [comment]
I'm not sure about `tracemem` however, because just because it gets copied doesn't mean another actual copy gets made, no? In my tests (below) I don't think tracemem tells the difference. I think `profmem` might be better.

Regardless, commenting out the `validObject` line of the assignment command reduces the time to what is expected. This is rather worrisome since we call `validObject` pretty much everytime we turn around, I think...

Here's my test (with the slightly bigger object, ceSim)
<pre>
> source("create_objects.R")
> system.time(replicate(100,clusterLegend(ceSim)[["cluster1"]][1, "color"] <- "red"))
   user  system elapsed 
  0.686   0.092   0.776 
> library(profmem)
> profmem(clusterLegend(ceSim)[["cluster1"]][1, "color"] <- "red")
Rprofmem memory profiling of:
clusterLegend(ceSim)[["cluster1"]][1, "color"] <- "red"

Memory allocations:
        bytes
1         184
2         184
3         184
4         200
5         176
6         200
7         296
8      183640
9      183640
10     183640
11     183640
... # Can't print all here, goes up to 326

</pre>

If save color matrix to object x:

<pre>
> x<-clusterLegend(ceSim)[["cluster1"]]
> system.time(replicate(100,x[1,"color"]<-"red"))
   user  system elapsed 
  0.001   0.000   0.002 
> profmem(x[1,"color"]<-"red")
Rprofmem memory profiling of:
x[1, "color"] <- "red"

Memory allocations:
      bytes      calls
1       184 <internal>
total   184    
</pre>

After Commented out validObject in code, more similar to that of simple x assignment above:
<pre>
> system.time(replicate(100,clusterLegend(ceSim)[["cluster1"]][1, "color"] <- "red"))
   user  system elapsed 
  0.076   0.003   0.079 
> profmem(clusterLegend(ceSim)[["cluster1"]][1, "color"] <- "red")
Rprofmem memory profiling of:
clusterLegend(ceSim)[["cluster1"]][1, "color"] <- "red"

Memory allocations:
      bytes      calls
1       184 <internal>
total   184
</pre>

**Comment by epurdom** [comment]
If I keep in the validObject command, but make our validity checks nothing (because validObject also checks superclasses), we don't have a huge memory leak either (3113200 bytes compared to 1424). So all of the validity checks are quite costly. 

<pre>
> #before do anything
> system.time(replicate(100,clusterLegend(ceSim)[["cluster1"]][1, "color"] <- "red"))
   user  system elapsed 
  1.006   0.092   1.094 
> p<-profmem(clusterLegend(ceSim)[["cluster1"]][1, "color"] <- "red")
> length(p$bytes)
[1] 328
> length(p$bytes[p$bytes>10000])
[1] 15
> total(p)
[1] 3113200
>  
> #Change code to remove all checks
> load_all()
> system.time(replicate(100,clusterLegend(ceSim)[["cluster1"]][1, "color"] <- "red"))
   user  system elapsed 
  0.171   0.003   0.175 
> p<-profmem(clusterLegend(ceSim)[["cluster1"]][1, "color"] <- "red")
> length(p$bytes)
[1] 7
> length(p$bytes[p$bytes>10000])
[1] 0
> total(p)
[1] 1424
</pre>


The most expensive part appears to be checking the transformation is valid and that assays (whether numeric and whether have NAs). If we remove that part of the validity check, our memory usage drops to 1093240 bytes, which is still an awfully expensive validity check, but a big reduction showing what is costing the most. 

But the amount of memory it still takes for the remaining (on a very small object!) makes me wonder if we should not create internal functions for different components of the checks, and call only the appropriate ones rather than calling validObject all of the time. It's dicey, because I feel like it has been quite useful, but at least on these basic assignment functions that we might be calling repeatedly in other functions it might make sense.

**Comment by drisso** [comment]
This is insane.... I'm wondering how much are we slowing down and consuming memory by calling `validObject` all the time.... should we just remove it?

Let's say that we keep it only for the constructor... what is the worst case that can happen?

**Comment by epurdom** [comment]
I have to say, I am not entirely sure of the reliability of profmem, etc. and whether my way of doing this is appropriately counting for memory (do I need a fresh R each time I change something?). But yes, this is my question too. 

I think we will (at times) need to replace validObject with something, hence my suggestion on compartmentalizing the validity checks into functions. The assignment of clusterLegend is a case in point, since we want to make sure the assignment the user gave has a valid form. Often we called validObject because we were quesy about something and new it often causes problems, like subsetting, where errors have been frequently caught because of validObject (e.g. added a slot about dendrogram stuff, and forgot that in subsetting throw away dendrogram, so need to throw away that slot too...). 

I'm thinking I'm going to go through the validObject calls and try to categorize them. 

And do you think we're really missing the boat somehow and doing something really wrong to get this memory problems? (or my memory checks are really wrong?) I'm slightly less surprised by the checking of the transformation and the assays, since that's manipulating and checking the big part of the object (though not that big with the test object I'm using), but even taking them out, it's surprisingly long for what seems like an accumulation of nothing checks.

**Comment by epurdom** [comment]
It also brings into question Martin's advice above, since calling new all over the place would call this expensive check. Should we take the assay and transformation checks out of the validity function and only put them in if an actual use of `clusterExperiment` function is called (assumes that the user wouldn't use the `new(...)` option very often). We might still want to pare back the use of the validObject calls, but it might make it slightly more feasible to call `validObject` when a lot of things have changed, or to use Martin's suggestion of calling `new` to avoid duplicating object. 

The subsetting command is an example where it would probably be safer anyway to call `new` rather than set to NULL all the things we want to drop to avoid errors like that I mentioned above.

**Comment by epurdom** [comment]
Just to point out how insane this memory problem is, `clusterSingle` calls `validObject`, so that every clustering run validates the object. Moreover, `clusterSingle` does that AFTER it has already called `clusterExperiment`. AND `clusterExperiment` itself calls `validObject` immediately after creating the object with a call to `new`!. So for every call of clusterSingle, that's 3 calls to validObject at a minimum. I think we weren't sure whether `new` would do the validity checks or not, so we put that in addition to be sure in many places. And then clusterMany calls it two more times along the way before returning the results. And if we used `primaryClusterIndex()<-` to assign the cluster index (instead of `@primaryClusterIndex<-` we called it again!). It's pretty scary how we've been using `validObject`. It's like our own little opioid epidemic running rampant inside our code where we've been prescribing it like nuts everywhere without realizing what we are doing. Thank goodness we never put the underlying subsampling and sequential functions into returning the clusterExperiment class.

After looking at the uses of `validObject`, here's my suggestion along the lines I suggested above:

1) remove the check on the assays and transformations except in calls to clusterExperiment, and even then allow for the user to not check (this because we call clusterExperiment in the code in places where we don't want to check, and I don't want to minimize code rewrite -- is that too lazy??)
2) Modularize the checks into functions, and try to replace as many of `validObject` as possible with the right check. There are many places where we call `validObject` but we've only changed one slot (I think the worst is things like replacement for the primaryClusterIndex). 
3) Get rid of the hidden duplicate calls, where we have layers of functions calling `validObject`
4) I'll consider adding Martin's suggestion, but only where there are many `@<-` assignments in a row, like subsetting so its worth calling validity checks (not just a single one like in clusterLegend).
@drisso, sound good? Anything else?

I'm going to have to check out a feature branch because it will take a while to make these changes. I'd love to know how much difference it makes. @drisso , do you have a moderately sized before example that you've timed that we can rerun for fun just to see? I don't think I have one with the timing saved.

**Comment by drisso** [comment]
I agree with all the points. I can't think of anything else right now.

I don't really have a recent example with timing, but I have a moderate sized example that I can re-run with both version (with and without validity checks) to compare the performance.

Just let me know when you're done with the feature branch and I will run it.

**Comment by epurdom** [comment]
This has been corrected and added into develop branch 46ad2f7 version 1.3.3-9002

**Comment by drisso** [comment]
OK, I will time my example with both the master and develop versions and let you know what is the speed-up.

**Comment by drisso** [comment]
FWI, I've tried the following RSEC commands with the master and develop versions of the package on a small but realistic dataset (10,983 genes by 232 cells):

```{r}
system.time(rsec <- RSEC(norm3, isCount = TRUE, minSizes = 5, alphas = 0.3,
             combineProportion = 0.5,
             mergeMethod = "adjP", mergeCutoff = 0.05,
             ncores = 7, random.seed = seed, run = TRUE))
```

Master version (1.3.3):

```{r}
   user  system elapsed 
345.010  74.489  48.635 
```

Develop version (1.3.3.9004):

```{r}
   user  system elapsed 
115.401  13.436  36.694 
```

**Comment by drisso** [comment]
This is what happens with 1 core:

Master:

```{r}
   user  system elapsed 
165.276  17.418 184.272
```

Develop:

```{r}
   user  system elapsed 
 80.253   7.954  88.468 
```

So, develop is twice as fast!

I've also re-run RSEC to have more clusterings:

```{r}
system.time(rsec <- RSEC(norm3, isCount = TRUE, minSizes = 5, alphas = c(0.1, 0.2, 0.3),
             combineProportion = 0.5, betas = c(0.9, 0.8),
             mergeMethod = "adjP", mergeCutoff = 0.05,
             ncores = 7, random.seed = seed, run = TRUE))
```

Master:

```{r}
    user   system  elapsed 
1463.972  165.346  301.334 
```

Develop:

```{r}
    user   system  elapsed 
1042.345  115.075  167.987 
```

Pretty consistently a 2x speed up!
