### ISSUE TITLE
makeDendrogram matrix version assumes numeric clusters

### ISSUE THREAD

**Issue by epurdom** [epurdom/clusterExperiment#22]
makeDendrogram matrix version assumes numeric clusters, but if send primaryClusterNamed(x) as the cluster, they are now characters.

**Comment by epurdom** [comment]
Could fix this by setting option of leaf label in plotDendrogram, and making makeDendrogram always on the numeric cluster.

**Comment by drisso** [comment]
Now it's fixed in makeDendrogram, meaning that it returns primaryCluster(x). Still needs to fix plotDendrogram so that it plots the correct leaf lables

**Comment by epurdom** [comment]
plotDendrogram is fixed so it does leaf labels.
