### ISSUE TITLE
plotReducedDims legend

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#236]
I get the following error in develop:

```{r}
> plotReducedDims(sce, reducedDim = "seurat_tsne", legend=FALSE)
Error in .local(object, whichCluster, ...) : 
  legend must either be logical or character value.
```

However the plot works as expected. 

The problem is that this if statement:
https://github.com/epurdom/clusterExperiment/blob/develop/R/plotReduceDim.R#L141
does not include the case where `legend` is logical but not TRUE.

@epurdom should I fix it in develop?

**Comment by epurdom** [comment]
Can you do a hot fix to the master branch? because I’ve already pushed develop to master and bioconductor as 1.99.0.

**Comment by drisso** [comment]
Sure! I'll do it soon!

**Comment by drisso** [comment]
Done!

Note that the develop branch is behind 15 commits. Shouldn't it be aligned with master now?

**Comment by epurdom** [comment]
Just fixed it. Thanks!
