### ISSUE TITLE
Change cluster names to m01 etc to have correct sorting

### ISSUE THREAD

**Issue by diyadas** [epurdom/clusterExperiment#254]
@rkchance and I are struggling a bit with the merged clusters being displayed (and counted) by plotHeatmap in alphabetical rather than numerical order, i.e. we get
m1 m10 m11 m12 ... m19 m2

we would like
m1 m2 m3 m4 ... m9 m10 m11 m12 ... m19

This is causing issues for the legend - we have color palettes that are in numerical order, and we'd also like the legend to display in that fashion.

a hacky solution would be changing the ordering to `clus.labels[order(as.numeric(gsub("m", "", clus.labels)))]]` but I'm not sure where to put something like that, and there's also probably a better way...

**Comment by rkchance** [comment]
It looks like there is a function in R that will deal with mixed character/number sorting by checking all number digits before making a sort call: [https://www.rdocumentation.org/packages/gtools/versions/3.5.0/topics/mixedsort].  
Maybe this could be a more useful sort method for cluster IDs with a character appended on the beginning?

**Comment by rkchance** [comment]
you need to load gtools, but it does the trick:

> alphanumer<- c("m1", "m10", "m2", "m11", "m3")
> cat(alphanumer)
m1 m10 m2 m11 m3
> library(gtools)
> mixedsort(alphanumer, decreasing=FALSE)
[1] "m1"  "m2"  "m3"  "m10" "m11"

**Comment by epurdom** [comment]
This is a continual problem, and while I can fix specific problems (and have in particular places) I think what I really need to do is change the names to be m01 etc so that the issue goes away permanently, rather than continually chasing examples of where it sorts badly. So I'm going to change the title of this issue to reflect that.

**Comment by epurdom** [comment]
For existing objects that already have been created, I would suggest changing the names of the clusters to `m01` etc manually using the function `renameClusters`. To automatically add zeros in front of the numbers, here is some code to play around that uses `str_pad` in `stringr` package to add zeros in front of numbers so certain number of digits. (`cl` is the existing names):
```
cl<-as.numeric(gsub("m","",cl)) #strip 'm' off; and I think its suppose to be numeric, but don't remember
pad<-if(length(unique(cl))<100) 2 else 3 #determine if maximum length is 2 or 3 in case in 100s
clPretty<-paste("m",stringr::str_pad(cl,width=pad,pad="0"),sep="")
```

**Comment by diyadas** [comment]
Any chance you could make it 001, etc.? I don't see it being an issue now but if we do merging on the Allen clusters this could pop up again.

**Comment by epurdom** [comment]
The code would add the number of digits necessary (that's what the code I
posted does)

**Comment by epurdom** [comment]
This has been done on 2.1.5-9001 (develop branch)
