### ISSUE TITLE
plotClustersTable(...plotType="bubble") scale is constant value

### ISSUE THREAD

**Issue by diyadas** [epurdom/clusterExperiment#260]
The scale for plotClustersTable bubble plots isn't working for me - it's one color instead of a gradient, though there are multiple colors in my plot:

![image](https://user-images.githubusercontent.com/7118569/47046904-16cbaf80-d14b-11e8-9976-927d0f988bf2.png)

**Comment by epurdom** [comment]
Diya, can you tell me what version your using and the call to `plotClustersTable`?

**Comment by diyadas** [comment]
R-3.5.0, clusterExperiment_2.1.5

`plotClustersTable(ce, whichClusters = 1:2, plotType="bubble") #ce is a clusterExperiment object`

**Comment by epurdom** [comment]
I have just pushed a change in the code that appropriately labels the plot so its clear what option has been chosen and doesn't color at all if plotting the total counts (2.1.5-9010). I put a question on slack as to what the best default would be but for now leaving it as NA, but at least clearer now what option was picked in looking at the plot.

**Comment by epurdom** [comment]
I have fixed the command so that if `margin=NA` there is no coloring of the points and no legend for the colors is plotted. (2.1.5-9011)
