### ISSUE TITLE
add function to make ClusterExperiment preserve numerical order?

### ISSUE THREAD

**Issue by diyadas** [epurdom/clusterExperiment#261]
As discussed, when I create a ClusterExperiment object with numerical cluster labels starting at 0, I have to convert to character. This results in the following order: 0, 1, 10, 11, 12, ..., 2, ...

If you could make the function in #254 an exported function, that would be really helpful.

thanks!

**Comment by epurdom** [comment]
I have just pushed an update to the develop branch that creates function `numericalToCharacter`. If it passes checks on TravisCI, then it should be fine to use the branch.

BTW, this branch now has update that changes class definition. You may need to run `updateObject` on old versions of ClusterExperiment. If you run into a problem with this, please let me know. (I shortly plan to added yet another change to the class, btw -- I'm trying to make these class changes before next bioconductor release at the end of this month).

**Comment by epurdom** [comment]
The class changes only affect the stored dendrograms...
