### ISSUE TITLE
Cluster genes along pseudotime 

### ISSUE THREAD

**Issue by flde** [epurdom/clusterExperiment#269]
Dear all, 

Many thanks for building this awesome tool! I use RSEC after tradeSeq to cluster genes along pseudotime. In that case I don't pass a genes x cells matrix but a pseudotime x gene matrix to RSEC with default settings (as done in the tradeSeq tutorial). The pseudotime is binned (N=50) and the expression values z-scored across the bins per gene.

I get really nice results but have the feeling I get too many clusters. So I went through the documentation and found that I can use makeConsensus or makeDendrogram + mergeClusters.

However, given that I use a z-scored pseudotime x gene matrix I am not sure if I can use makeDendrogram without modifications. Because by default makeDendrogram computes the DEA between cluster of cells. In my case it would be the z-score between cluster of genes. Hence a cluster of genes would be merged with another if the z-scores are not different across binned pseudotime under a threshold. Does that make sense? 

My questions would be if you have an advice to correctly set the parameters of makeDendrogram in that case. Or should I just omit the makeDendrogram + mergeClusters workflow and use the makeConsensus proportion parameter to reduce the number of clusters?

Pardon my long question but I would highly appreciate your help and hope the thread helps others which are using your package for trajectory analysis. 

Best wishes, 
Florian

**Comment by Abeer-hes** [comment]
Hello @RSEQ,

I second on Florian request as I am as well willing to get more summarized clusters downstream of tradeseq analysis.
Any help how to best follow on that will be appreciated.

**Comment by flde** [comment]
I ended up using clusterMany since that is a very helpful to figure out whats going on. Guess overall my question is not really a clusterExperiment issue and the documentation is very well written to look up the inner workings - so I would close for now. Many thanks for the tool! 

Best wishes, 
Florian
