### ISSUE TITLE
run only selected method in mergeClusters?

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#39]
Currently, mergeClusters will compute significance for all methods and then use only the selected one.

Should we turn it into a switch that compute only the selected one?

```
  sigByNode <- by(sigTable, sigTable$ContrastName, function(x) {
    mb <- .myTryFunc(pvalues=x$P.Value, FUN=.m1_MB)
    locfdr <- .myTryFunc(tstats=x$t, FUN=.m1_locfdr)
    jc <- .myTryFunc(tstats=x$t, FUN=.m1_JC)
    return(c("adjP"=.m1_adjP(x$adj), "locfdr"=locfdr, "MB"=mb,"JC"=jc))
  })
```

**Comment by epurdom** [comment]
I think I did this because you might want the plot to have all of them, but only make merge cluster on one of them. maybe we can think of a more elegant solution.

**Comment by drisso** [comment]
Make the try() silent, to avoid messages like the following:
```
Error in locfdr::locfdr(tstats, plot = 0) : 
  ML estimation failed.  Rerun with nulltype=2
```

**Comment by epurdom** [comment]
Made the try silent, but there are still warnings...

**Comment by epurdom** [comment]
I've changed it so it only runs the method requested. So if you ask plot all, then runs all, even if mergeMethod="none".  Etc.
