### ISSUE TITLE
problem if arguments given to clusterDArgs etc and not needed in compareChoices

### ISSUE THREAD

**Issue by InfH** [epurdom/clusterExperiment#5]
Arguments that only work with 'hierarchical' (under clusterDArgs) will throw error for the "tight" so that can't do clusterMethod=c("hierarchical","tight") with these cluster Args. Should at least give a reasonable error, if can't handle it.

example:
compareTCL <-compareChoices(pam_obj[[i]]$x[,1:npcs], ks=2:15, clusterMethod=c("hierarchical", "tight"), alphas=0.1,subsample=TRUE, sequential=TRUE, ncores=ncores, removeSil=TRUE, findBestK=TRUE,
                        subsampleArgs=list(resamp.num=100,ncores=1,clusterFunction="kmeans",clusterArgs=list(nstart=10)), 
                        seqArgs=list(beta=0.9,k.min=3, top.can=5), 
                        clusterDArgs=list(min.size=5, verbose=FALSE,
                                          clusterArgs=list(evalClusterMethod=c("average"))), random.seed=seed, run=TRUE)

**Comment by epurdom** [comment]
Hi Diya,
I think I now have fixed it in the develop version so it gives a warning instead of stopping. Could you try it?

I recognize that the warning will spit out a lot, so I should fix this for compareChoices. So I am not closing this issue regardless.
Elizabeth

**Comment by epurdom** [comment]
This has actually been fixed awhile ago with the 'checkArgs' option to clusterD
