### ISSUE TITLE
results of clusterMany do not save colData

### ISSUE THREAD

**Issue by epurdom** [epurdom/clusterExperiment#52]
running 

`ce<-clusterMany(fluidigm, clusterFunction="pam",ks=2:10,removeSil=c(TRUE,FALSE), isCount=TRUE)`

results in a ClusterExperiments object with 0 columns of colData. I.e. it doesn't preserve the colData of fluidigm.

**Comment by epurdom** [comment]
This seems to be fixed now, but I don't know if we've systematically checked. Can we close this one?

**Comment by drisso** [comment]
I've added tests to all the relevant functions (commit 12d0e973de7b22b16a269cb7257c4935a0b2fbe9).
