### ISSUE TITLE
makeDendrogram for ClusterExperiment object fails with unassigned="remove"

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#54]
It violates the check that the number of leaves in the dendrogram must be the same as the number of samples in the object.

I think that this option should be used only for the matrix method, it doesn't really make sense for ClusterExperiment. Especially because one can explicitly use removeUnclustered.

**Comment by epurdom** [comment]
I agree, though removeUnclustered will just delete the dendrogram, not make new dendrogram without the samples.

**Comment by epurdom** [comment]
Now the clusterExperiment version doesn't not allow "remove" and I put an explanation in the help files that it is only an option for the matrix version. 
Currently this is fixed in a feature branch that I will merge after fixing other bugs.
