### ISSUE TITLE
Should alphas be inverted?

### ISSUE THREAD

**Issue by epurdom** [epurdom/clusterExperiment#70]
Should we change alpha to 1-current value, so that larger alpha implies a larger amount of similarity requested of the clustering?

**Comment by drisso** [comment]
I don't have a strong opinion about this. The current way of setting alpha is more consistent with the tight clustering package, so that could be a plus. But if the interpretation is clearer with 1-alpha, I'm fine with changing it.

**Comment by epurdom** [comment]
Decided to leave it alone.
