### ISSUE TITLE
makeDendrogram or workflow bug -- can wind up with dendro_samples but not dendro_clusters

### ISSUE THREAD

**Issue by epurdom** [epurdom/clusterExperiment#73]
In running the vignette, I wound up with a CE object that had dendro_samples but not dendro_clusters. I don't know how that happened, but it seems like if I created one the other should be there. Similarly, if one got deleted, both should get deleted.

Unfortunately, I don't know how to recreate this right now, and I'm doing other things.

**Comment by epurdom** [comment]
I think this should be a part of the validity check for the object -- that it doesn't have 1 without the other. Sound okay to you?

**Comment by drisso** [comment]
Sounds good to me.

**Comment by epurdom** [comment]
Okay, so now I remember what happened. I think we decided at some point its nice to have the samples clustered by the combineMany output rather than mergeClusters, because could more easily compare them, which is why mergeClusters deleted one of them and not the other. 

We could run an internal fix, where we keep the old sample one, but make a cluster one based on mergeClusters. The problem is that to run getBestFeatures on the output of mergeClusters, you will need to rerun makeDendrogram anyway, which will overwrite it regardless, so I think this idea of keeping the sample dendrogram around isn't useful. 

I'm thinking that the best would be to delete both after mergeClusters. But in the more detailed vignette part, perhaps under plotHeatmap, we can mention that it can be useful to reset the primaryClusterIndex and redo dendrogram for good ordering of the clusterings. I think we should also go back to primaryClusterIndex resets deleting the dendrograms, if we undid that at some point.

**Comment by epurdom** [comment]
On my feature line, I have implemented it as described above.

**Comment by epurdom** [comment]
This has been merged into development line now.
