### ISSUE TITLE
seqCluster: no visible binding for global variable ‘tempSubsampleArgs’

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#79]
When running R CMD check this causes a NOTE.

Indeed, `tempSubsampleArgs` is used in lines 215 and 236 of seqCluster.R but is never defined.

**Comment by drisso** [comment]
It's defined in seqCluster.R in master as
```{r}
tempSubsampleArgs<-c(list(k=k + i - 1),subsampleArgs)
```

@epurdom is there a reason why it was removed in develop or should it be added back?

**Comment by epurdom** [comment]
Yes, I saw this warning. 
However, I do not think it shouldn’t be like master, because in fact I fixed something that wasn’t working, I think. But I think I have fixed it.  I just need to run some tests.
