### ISSUE TITLE
Change defaults to clusterMany or underlying functions

### ISSUE THREAD

**Issue by epurdom** [epurdom/clusterExperiment#81]
For historical reasons, some of the arguments to `clusterDArgs`, `subsampleArgs` and `seqArgs` are set by `clusterMany` to be different than the defaults described in `clusterD`, `subsampleClustering` and `seqCluster`. 
Given how the pipeline works now, and that clusterMany is THE function to use, then it seems to make sense to make the defaults in `clusterD`, `subsampleClustering` and `seqCluster` be those set in clusterMany and remove them from clusterMany.

**Comment by epurdom** [comment]
Should we also reconsider these defaults?

**Comment by epurdom** [comment]
Davide, do you have an opinion on this? I'm thinking by setting them explicitly in clusterMany, the user sees them. So that's good (they may never look at the help that shows these defaults). Also, should these be the defaults do you think?

**Comment by drisso** [comment]
I agree, setting them in clusterMany is better. I'm not sure about the "right" defaults... what you use in the quick start section of the vignette is probably the most sensible choice, no?
