### ISSUE TITLE
log transformation -- what base should it be?

### ISSUE THREAD

**Issue by epurdom** [epurdom/clusterExperiment#84]
We currently probably use e, but log2 or log10 would be better. Just needs a change in the underlying transformation function done by default.
voom is log2. And the offset it +0.5, not +1. Should we follow that for consistency?

**Comment by drisso** [comment]
Log2 is fine with me (better than log10 for consistency with other tools).

The advantage of +0.5 is that you can distinguish 0 from 1, but may be annoying to have negative numbers in the heatmap?

**Comment by epurdom** [comment]
I don't understand -- can't you always distinguish 0 from 1?

That is a good point about negative. On the other hand, it is common to add something that is less than the smallest non-zero value, which would make 0.5 better. We should decide before we submit.

I will change it to log2, but not the offset at this time.

**Comment by drisso** [comment]
> I don't understand -- can't you always distinguish 0 from 1?

Sorry, I meant that if one doesn't pay attention to the value of the offset, they might assume 0 = log(1).

I agree with your point, but on the other hand log+1 is kind of standard, it even has its own function (log1p).

A point in favor of using natural log and log+1 is computation accuracy, through the log1p() and expm1() functions, see the log man page.

**Comment by drisso** [comment]
See e.g.,

```{r}
> exp(log(1e-5+1)-1)
[1] 0.3678831
> expm1(log1p(1e-5))
[1] 1e-05
```

Not sure how much important in our case...

**Comment by drisso** [comment]
See e.g.

```{r}
> exp(log(1e-20+1))-1
[1] 0
> expm1(log1p(1e-20))
[1] 1e-20
```

**Comment by epurdom** [comment]
Especially since this is only suppose to a transformation for count data, so we shouldn't be taking log of small values. If it is FPKM, that is a different question, though +1 probably doesn't make sense for FPKM anyway since I think 1 is a large value.
I'll keep the offset at 1, and I've made a note that voom does 0.5
