### ISSUE TITLE
Should we have a coercion method from ClusterExperiment to SummarizedExperiment?

### ISSUE THREAD

**Issue by drisso** [epurdom/clusterExperiment#87]
i.e., would
```{r}
as(cl, "SummarizedExperiment")
```
work if cl is a ClusterExperiment object?

(I'm opening the issue because I cannot test it right now and I don't want to forget).

**Comment by epurdom** [comment]
It actually already works. Its automatic from the class inherentance apparently.

**Comment by drisso** [comment]
Good to know, thanks.
