### ISSUE TITLE
hard to redo mergeClusters

### ISSUE THREAD

**Issue by epurdom** [epurdom/clusterExperiment#89]
If you want to rerun mergeClusters with a different parameter choice, then its actually a bit annoying, because mergeClusters sets the primary index to the new merged cluster and deletes the dendrograms.

So then you have to figure out which is the index of the combineMany and set it as primary so you can remake the dendrogram and rerun mergeClusters. 

I guess we could encourage to actually just run the mergeClusters without merging to decide, so less likely to want to rerun it...

**Comment by drisso** [comment]
Or you could save it as a different object?

**Comment by epurdom** [comment]
This is now fixed with the new system of how deal with dendrograms.
